// SV-42: Service Worker（sw.js）の手書きのテンプレート。DOM に触れない純粋な関数だけ。
// vite.config.ts のプラグインがビルドの最後に dist の一覧と版を渡して sw.js を書く（依存パッケージを使わない）。
// sw.js の本文が使う自由な識別子は self・caches・fetch・Request・URL だけ（テストで差し替えて評価するため）。
// 本文は文字列なので日本語を書かない（tests/architecture.test.ts の §3-10 の検査の対象）。
// 振る舞い: install で全部を wizlike-{版} に入れて待機（skipWaiting はページの message でだけ）、
// ナビゲーションはネットワーク優先（失敗したらキャッシュの index.html）、それ以外はキャッシュ優先。

/** SV-42: プリキャッシュに入れない名前（sw.js 自身、*.map、"." で始まる名前の段を含むもの） */
function excluded(path: string): boolean {
  if (path === "sw.js") return true;
  if (path.endsWith(".map")) return true;
  return path.split("/").some((seg) => seg.startsWith("."));
}

/**
 * SV-42: プリキャッシュの URL の一覧。パスは dist からの相対（"/" 区切り）。
 * "./" + path、昇順、重複なし。"index.html" が無ければ例外（ナビゲーションで返すため）
 */
export function precacheUrls(paths: readonly string[]): string[] {
  const kept = [...new Set(paths.map((p) => p.replace(/\\/g, "/").replace(/^\.?\//, "")))].filter((p) => !excluded(p));
  if (!kept.includes("index.html")) throw new Error("precacheUrls: index.html is missing");
  return kept.sort().map((p) => "./" + p);
}

/** SV-42: sw.js の本文。version はファイルの中身から作った版（キャッシュ名 wizlike-{version}） */
export function renderServiceWorker(o: { version: string; urls: readonly string[] }): string {
  return `// generated by vite.config.ts (wizlike-sw). Do not edit.
const VERSION = ${JSON.stringify(o.version)};
const CACHE = "wizlike-" + VERSION;
const URLS = ${JSON.stringify(o.urls)};
const INDEX = "./index.html";
const abs = (u) => new URL(u, self.registration.scope).href;
self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // bypass the HTTP cache so that stale files never enter the new cache
    await cache.addAll(URLS.map((u) => new Request(abs(u), { cache: "reload" })));
    // no skipWaiting here: an update waits until the page asks (message "skipWaiting") or every tab is closed
  })());
});
self.addEventListener("message", (e) => {
  if (e.data && e.data.type === "skipWaiting") e.waitUntil(self.skipWaiting());
});
self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith("wizlike-") && k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (req.mode === "navigate") {
      // index.html: network first, the cached copy when offline or the server fails (never written back to the cache)
      try {
        const res = await fetch(req);
        if (res.ok) return res;
        return (await cache.match(abs(INDEX))) || res;
      } catch (err) {
        const hit = await cache.match(abs(INDEX));
        if (hit) return hit;
        throw err;
      }
    }
    // hashed assets (assets/) and the other precached files: cache first, the network when missing
    return (await cache.match(req)) || fetch(req);
  })());
});
`;
}
